"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
from pathlib import Path
import dotenv
import dj_database_url # Importamos para la BBDD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Cargar variables de entorno ---
# Esto lee tu archivo .env (que NO está en GitHub)
dotenv.load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Configuración de Seguridad (Leída desde .env) ---
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# DEBUG se lee desde .env. Si no se encuentra, es False por seguridad.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Ajusta esto para producción (Railway pondrá su propio host)
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Apps de Terceros ---
    'rest_framework',     # Para construir la API REST
    'corsheaders',        # Para permitir peticiones del Frontend
    
    # --- Apps de nuestra Arquitectura Limpia ---
    'adapters.api.apps.ApiConfig',
    'adapters.infrastructure.apps.InfrastructureConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # --- Middleware de CORS (Debe ir antes de CommonMiddleware) ---
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- Base de Datos (PostgreSQL) ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Lee la variable DATABASE_URL de tu archivo .env
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600 # Opcional: tiempo de vida de la conexión
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# --- Internacionalización y Localización (Ecuador) ---
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Django REST Framework (DRF) ---
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # Por ahora, permitimos el acceso a cualquiera.
        # Luego lo cambiaremos por 'IsAuthenticated' con JWT.
        'rest_framework.permissions.AllowAny',
    ]
}

# --- Configuración de CORS (Cross-Origin Resource Sharing) ---
# Por ahora, permitimos que cualquier frontend se conecte (ideal para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True 
# En producción, deberías cambiar esto a:
# CORS_ALLOWED_ORIGINS = [
#     "https://tu-frontend.com",
# ]


# --- CONFIGURACIÓN PARA EL SRI (Leído desde .env) ---
# Esta sección alimenta a tu 'DjangoSRIService'
try:
    SRI_FIRMA_PASS = os.getenv('SRI_FIRMA_PASS')
    
    # ¡¡¡IMPORTANTE!!! 
    # Reemplaza 'nombre_de_tu_firma.p12' con el nombre real de tu archivo
    # que guardaste en la carpeta /secrets/
    SRI_FIRMA_PATH = BASE_DIR / 'secrets' / 'el-arbolito.p12'
    
    # Datos del Emisor (Junta de Riego)
    SRI_EMISOR_RUC = os.getenv('SRI_EMISOR_RUC')
    SRI_EMISOR_RAZON_SOCIAL = os.getenv('SRI_EMISOR_RAZON_SOCIAL')
    SRI_EMISOR_DIRECCION_MATRIZ = os.getenv('SRI_EMISOR_DIRECCION_MATRIZ')
    SRI_NOMBRE_COMERCIAL = os.getenv('SRI_NOMBRE_COMERCIAL')
    
    # Series
    SRI_SERIE_ESTABLECIMIENTO = os.getenv('SRI_SERIE_ESTABLECIMIENTO')
    SRI_SERIE_PUNTO_EMISION = os.getenv('SRI_SERIE_PUNTO_EMISION')
    
    # Ambiente y URLs
    SRI_AMBIENTE = os.getenv('SRI_AMBIENTE', '1') # '1' (Pruebas) por defecto
    SRI_URL_RECEPCION = os.getenv('SRI_URL_RECEPCION')
    SRI_URL_AUTORIZACION = os.getenv('SRI_URL_AUTORIZION')

    # Validador para asegurar que los archivos y secretos existen
    if not SRI_FIRMA_PASS or not SRI_FIRMA_PATH.exists():
        raise ValueError("Error: Falta la firma (SRI_FIRMA_PATH) o la contraseña (SRI_FIRMA_PASS). Revisa tu .env y la carpeta /secrets/")
    if not SRI_EMISOR_RUC:
        raise ValueError("Error: Falta el RUC del emisor (SRI_EMISOR_RUC). Revisa tu .env")

except Exception as e:
    # Si algo falla al cargar, la aplicación no se iniciará.
    print(f"Error CRÍTICO al cargar la configuración del SRI: {e}")
    raise e