"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.x
Editado para Arquitectura Limpia + Facturación SRI + Notificaciones Email.
"""

import os
from pathlib import Path
from datetime import timedelta # Para configurar la duración del Token JWT
import dotenv # Requiere: pip install python-dotenv
import dj_database_url # Requiere: pip install dj-database-url

# ==============================================================================
# 1. CONFIGURACIÓN BÁSICA Y RUTAS
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR apunta a la carpeta raíz donde está manage.py
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CARGAR VARIABLES DE ENTORNO ---
# Leemos el archivo .env ubicado en la raíz.
# Esto es vital para seguir la metodología "12-Factor App".
dotenv_path = BASE_DIR / '.env'
if dotenv_path.exists():
    dotenv.load_dotenv(dotenv_path)
else:
    print("⚠️ ADVERTENCIA: No se encontró el archivo .env en la raíz del proyecto.")

# ==============================================================================
# 2. SEGURIDAD
# ==============================================================================

# La llave secreta para firmar sesiones y tokens. NUNCA la subas a GitHub.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-default-key-for-dev')

# DEBUG debe ser True solo en desarrollo. En producción, ponlo en False en el .env
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*'] # En producción, pon aquí tu dominio: ['api.juntaarbolito.com']


# ==============================================================================
# 3. APLICACIONES INSTALADAS
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Apps de Terceros ---
    'rest_framework',           # El motor de la API
    'rest_framework_simplejwt', # Autenticación por Tokens (JWT)
    'corsheaders',              # Permite que Angular/React/Vue consuman la API
    'drf_yasg',                 # Documentación automática (Swagger)

    # --- Módulos de Arquitectura Limpia (Tu Tesis) ---
    # Registramos los adaptadores para que Django detecte modelos, comandos y admin.
    'adapters.api.apps.ApiConfig',
    'adapters.infrastructure.apps.InfrastructureConfig',
]

# ==============================================================================
# 4. MIDDLEWARE (Intermediarios de Peticiones)
# ==============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # ¡IMPORTANTE! CorsMiddleware debe ir lo más arriba posible,
    # antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================================================
# 5. BASE DE DATOS
# ==============================================================================

# Usamos dj_database_url para parsear la URL del .env
# Ejemplo: mysql://usuario:password@localhost:3306/nombre_db
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=False # Cambiar a True si usas DB en la nube (AWS/Azure)
    )
}


# ==============================================================================
# 6. VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ==============================================================================
# 7. INTERNACIONALIZACIÓN (Localización Ecuador)
# ==============================================================================

LANGUAGE_CODE = 'es-ec'  # Español de Ecuador

# UTC es el estándar para guardar en BDD (recomendado)
# Django convertirá a hora local al mostrarlo.
TIME_ZONE = 'America/Guayaquil'

USE_I18N = True
USE_TZ = True # ¡Esto es lo importante! Activa el soporte de zonas horarias


# ==============================================================================
# 8. ARCHIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Descomentar para producción

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# 9. CONFIGURACIÓN DRF & JWT (Seguridad de API)
# ==============================================================================

REST_FRAMEWORK = {
    # Por defecto, todo endpoint requiere estar logueado.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Usamos JWT para autenticar.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    # El token de acceso dura 60 minutos (ajustable)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # El token de refresco dura 1 día (permite renovar sesión sin loguearse de nuevo)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# ==============================================================================
# 10. CORS (Permisos de Acceso Frontend)
# ==============================================================================

# En desarrollo permitimos todo. En producción, especifica tu dominio.
CORS_ALLOW_ALL_ORIGINS = True


# ==============================================================================
# 11. CONFIGURACIÓN DEL SRI (Facturación Electrónica)
# ==============================================================================
# Esta sección carga las credenciales y rutas críticas para firmar facturas.

try:
    # A. Credenciales
    SRI_FIRMA_PASS = os.getenv('SRI_FIRMA_PASS')

    # B. Rutas de Archivos (Clave para tu Tesis)
    # Definimos dónde Django debe buscar el archivo .p12 y el .jar
    # Se recomienda crear una carpeta 'secrets' en la raíz para el .p12
    SRI_FIRMA_PATH = BASE_DIR / 'secrets' / 'el_arbolito.p12'

    # Ruta al JAR que firma (Extraída del proyecto A)
    SRI_JAR_PATH = BASE_DIR / 'adapters' / 'infrastructure' / 'files' / 'jar' / 'sri.jar'

    # C. Datos del Emisor (Leídos del .env)
    SRI_EMISOR_RUC = os.getenv('SRI_EMISOR_RUC')
    SRI_EMISOR_RAZON_SOCIAL = os.getenv('SRI_EMISOR_RAZON_SOCIAL')
    SRI_EMISOR_DIRECCION_MATRIZ = os.getenv('SRI_EMISOR_DIRECCION_MATRIZ')
    SRI_NOMBRE_COMERCIAL = os.getenv('SRI_NOMBRE_COMERCIAL')

    # D. Configuración Técnica
    SRI_SERIE_ESTABLECIMIENTO = os.getenv('SRI_SERIE_ESTABLECIMIENTO')
    SRI_SERIE_PUNTO_EMISION = os.getenv('SRI_SERIE_PUNTO_EMISION')
    SRI_AMBIENTE = int(os.getenv('SRI_AMBIENTE', '1')) # 1=Pruebas, 2=Producción
    SRI_OBLIGADO_CONTABILIDAD = 'SI'

    # E. Web Services
    SRI_URL_RECEPCION = os.getenv('SRI_URL_RECEPCION')
    SRI_URL_AUTORIZACION = os.getenv('SRI_URL_AUTORIZACION')

    # --- VALIDACIÓN DE INICIO (Fail Fast) ---
    # El sistema no iniciará si faltan archivos críticos.

    if not SRI_FIRMA_PASS:
        print("⚠️ ADVERTENCIA SRI: Variable SRI_FIRMA_PASS no definida en .env")

    if not SRI_EMISOR_RUC:
        print("⚠️ ADVERTENCIA SRI: Variable SRI_EMISOR_RUC no definida en .env")

    # Verificamos existencia física de archivos (Solo si estamos corriendo servidor)
    # Usamos os.environ.get('RUN_MAIN') para que no falle al hacer migraciones simples
    if os.getenv('RUN_MAIN') == 'true':
        if not SRI_FIRMA_PATH.exists():
            print(f"❌ ERROR CRÍTICO SRI: No se encuentra el archivo de firma en: {SRI_FIRMA_PATH}")
            print("   -> Por favor coloca tu archivo .p12 en la carpeta 'secrets/' de la raíz.")

        if not SRI_JAR_PATH.exists():
            print(f"❌ ERROR CRÍTICO SRI: No se encuentra el archivo sri.jar en: {SRI_JAR_PATH}")
            print("   -> Por favor copia el .jar del Proyecto A a esa ruta.")

except Exception as e:
    print(f"❌ Error cargando configuración SRI en settings.py: {e}")


# ==============================================================================
# 12. CONFIGURACIÓN DE CORREO ELECTRÓNICO (GMAIL)
# ==============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Credenciales leídas del archivo .env para seguridad
# Asegúrate de generar una "Contraseña de Aplicación" en tu cuenta Google
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Dirección por defecto que aparecerá en "De:"
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print("⚠️ ADVERTENCIA EMAIL: Credenciales de correo no configuradas en .env (EMAIL_HOST_USER / EMAIL_HOST_PASSWORD)")

# Al final de tu settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')