# Generated by Django 5.2.7 on 2026-01-16 11:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrios',
            },
        ),
        migrations.CreateModel(
            name='FacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ANULADA', 'ANULADA')], default='PENDIENTE', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sri_ambiente', models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCION')], default=1)),
                ('sri_tipo_emision', models.PositiveIntegerField(choices=[(1, 'NORMAL')], default=1)),
                ('clave_acceso_sri', models.CharField(blank=True, db_index=True, max_length=49, null=True, unique=True)),
                ('estado_sri', models.CharField(blank=True, help_text='Estado devuelto por el SRI (RECIBIDA, AUTORIZADO, etc)', max_length=50, null=True)),
                ('fecha_autorizacion_sri', models.DateTimeField(blank=True, null=True)),
                ('xml_autorizado_sri', models.TextField(blank=True, null=True)),
                ('mensaje_error_sri', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'db_table': 'facturas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='LecturaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Lectura (m3)')),
                ('lectura_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lectura Anterior (m3)')),
                ('consumo_del_mes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Consumo Calculado (m3)')),
                ('fecha', models.DateField(verbose_name='Fecha de Toma')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('esta_facturada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'lecturas',
                'ordering': ['-fecha'],
                'get_latest_by': 'fecha',
            },
        ),
        migrations.CreateModel(
            name='MedidorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Serial')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('lectura_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo/Suspendido'), ('DANADO', 'Dañado'), ('ROBADO', 'Robado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'db_table': 'medidores',
            },
        ),
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEDIDO', 'Medido (Con Medidor)'), ('FIJO', 'Tarifa Fija (Sin Medidor)')], default='FIJO', max_length=20)),
                ('valor_tarifa', models.DecimalField(decimal_places=2, default=3.0, help_text='Valor mensual para tarifa fija', max_digits=10)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio de Agua',
                'db_table': 'servicios_agua',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='infrastructure.facturamodel')),
            ],
            options={
                'db_table': 'facturas_detalles',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='lectura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.lecturamodel'),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='infrastructure.medidormodel', verbose_name='Medidor Asociado'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.medidormodel'),
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Número de comprobante o referencia bancaria', max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='infrastructure.facturamodel')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Vincula la factura al contrato de servicio específico (Fijo o Medido)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='infrastructure.serviciomodel'),
        ),
        migrations.CreateModel(
            name='SocioModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Referencia exacta del domicilio', max_length=200, null=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('TESORERO', 'TESORERO'), ('OPERADOR', 'OPERADOR'), ('SOCIO', 'SOCIO')], default='SOCIO', max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='infrastructure.barriomodel', verbose_name='Barrio de Domicilio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socios',
            },
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='infrastructure.sociomodel'),
        ),
        migrations.CreateModel(
            name='MultaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(help_text='Ej: Falta a Minga Noviembre', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('factura_id', models.IntegerField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='infrastructure.sociomodel')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='infrastructure.sociomodel'),
        ),
        migrations.CreateModel(
            name='TerrenoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(help_text='Ej: Lote vacío frente a la escuela', max_length=200, verbose_name='Dirección/Referencia')),
                ('es_cometida_activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terrenos_ubicados', to='infrastructure.barriomodel')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='infrastructure.sociomodel')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
                'db_table': 'terrenos',
            },
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='infrastructure.terrenomodel'),
        ),
        migrations.AddField(
            model_name='medidormodel',
            name='terreno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidor', to='infrastructure.terrenomodel', verbose_name='Ubicación (Terreno)'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturamodel',
            unique_together={('medidor', 'fecha')},
        ),
    ]
