# Generated by Django 5.2.7 on 2025-11-11 02:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Pagada', 'PAGADA'), ('Anulada', 'ANULADA')], default='Pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('clave_acceso_sri', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('estado_sri', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje_sri', models.TextField(blank=True, null=True)),
                ('xml_enviado_sri', models.TextField(blank=True, null=True)),
                ('xml_respuesta_sri', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='LecturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateField()),
                ('lectura_actual_m3', models.PositiveIntegerField()),
                ('lectura_anterior_m3', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Lectura',
                'db_table': 'lecturas',
                'get_latest_by': 'fecha_lectura',
            },
        ),
        migrations.CreateModel(
            name='MedidorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('tiene_medidor_fisico', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medidor',
                'db_table': 'medidores',
            },
        ),
        migrations.CreateModel(
            name='SocioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'ADMINISTRADOR'), ('Tesorero', 'TESORERO'), ('Operador', 'OPERADOR'), ('Socio', 'SOCIO')], default='Socio', max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'db_table': 'socios',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='infrastructure.facturamodel')),
            ],
            options={
                'db_table': 'facturas_detalles',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='lectura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.lecturamodel'),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='infrastructure.medidormodel'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='medidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.medidormodel'),
        ),
        migrations.AddField(
            model_name='medidormodel',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='infrastructure.sociomodel'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='infrastructure.sociomodel'),
        ),
    ]
