# Generated by Django 5.2.10 on 2026-02-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaOrdenTrabajoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Foto o documento de respaldo', upload_to='evidencias_ordenes/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='infrastructure.ordentrabajomodel')),
            ],
            options={
                'verbose_name': 'Evidencia de Orden',
                'verbose_name_plural': 'Evidencias de Órdenes',
                'db_table': 'evidencias_orden_trabajo',
            },
        ),
    ]
