# Generated by Django 5.2.7 on 2026-01-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(help_text='Ej: Falta a Minga Noviembre', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('factura_id', models.IntegerField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='infrastructure.sociomodel')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Número de comprobante o referencia bancaria', max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='infrastructure.facturamodel')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
    ]
