# Generated by Django 6.0.1 on 2026-01-26 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('MINGA', 'MINGA'), ('SESION', 'SESION'), ('APORTE', 'APORTE')], max_length=20)),
                ('fecha', models.DateField()),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('FINALIZADO', 'FINALIZADO')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'gobernanza_evento',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('estado_justificacion', models.CharField(choices=[('SIN_SOLICITUD', 'SIN_SOLICITUD'), ('PENDIENTE', 'PENDIENTE'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA')], default='SIN_SOLICITUD', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multa_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_gobernanza', to='infrastructure.facturamodel')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='infrastructure.sociomodel')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='infrastructure.eventomodel')),
            ],
            options={
                'db_table': 'gobernanza_asistencia',
                'unique_together': {('evento', 'socio')},
            },
        ),
    ]
