# Generated by Django 5.2.7 on 2025-12-24 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturamodel',
            options={'get_latest_by': 'fecha', 'ordering': ['-fecha'], 'verbose_name': 'Lectura', 'verbose_name_plural': 'Lecturas'},
        ),
        migrations.RemoveField(
            model_name='lecturamodel',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='lecturamodel',
            name='lectura_actual_m3',
        ),
        migrations.RemoveField(
            model_name='lecturamodel',
            name='lectura_anterior_m3',
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='esta_facturada',
            field=models.BooleanField(default=False, help_text='Indica si esta lectura ya entró en una factura'),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='fecha',
            field=models.DateField(default='2025-01-01', verbose_name='Fecha de Toma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Lectura (m3)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturamodel',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='infrastructure.medidormodel', verbose_name='Medidor Asociado'),
        ),
        migrations.AlterField(
            model_name='medidormodel',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo/Suspendido'), ('DANADO', 'Dañado'), ('ROBADO', 'Robado'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='medidormodel',
            name='terreno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidor', to='infrastructure.terrenomodel', verbose_name='Ubicación (Terreno)'),
        ),
    ]
