# Generated by Django 5.2.10 on 2026-02-07 10:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductoMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(db_index=True, help_text='SKU o Código Auxiliar para SRI', max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Precio base sin impuestos', max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('graba_iva', models.BooleanField(default=True, verbose_name='Graba IVA')),
                ('codigo_impuesto_sri', models.CharField(default='2', help_text='2=IVA, 0=0%, 6=No Objeto', max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(blank=True, db_constraint=False, help_text='Rubro contable asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.catalogorubromodel')),
            ],
            options={
                'verbose_name': 'historical Material / Producto',
                'verbose_name_plural': 'historical Inventario de Materiales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(help_text='SKU o Código Auxiliar para SRI', max_length=50, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, help_text='Precio base sin impuestos', max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('graba_iva', models.BooleanField(default=True, verbose_name='Graba IVA')),
                ('codigo_impuesto_sri', models.CharField(default='2', help_text='2=IVA, 0=0%, 6=No Objeto', max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('rubro', models.ForeignKey(help_text='Rubro contable asociado', on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='infrastructure.catalogorubromodel')),
            ],
            options={
                'verbose_name': 'Material / Producto',
                'verbose_name_plural': 'Inventario de Materiales',
                'db_table': 'inventario_materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
