# Generated by Django 5.2.7 on 2026-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagomodel",
            name="comprobante_imagen",
            field=models.ImageField(
                blank=True,
                help_text="Foto del recibo subida por el socio",
                null=True,
                upload_to="comprobantes/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="pagomodel",
            name="validado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="facturamodel",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "PENDIENTE"),
                    ("POR_VALIDAR", "POR_VALIDAR"),
                    ("PAGADA", "PAGADA"),
                    ("ANULADA", "ANULADA"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
