# Generated by Django 6.0.1 on 2026-01-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_eventomodel_asistenciamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturamodel',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='RIDE (PDF) generado', null=True, upload_to='comprobantes/pdf/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='archivo_xml',
            field=models.FileField(blank=True, help_text='Archivo XML autorizado por el SRI', null=True, upload_to='comprobantes/xml/%Y/%m/'),
        ),
    ]
