# Generated by Django 5.2.7 on 2026-01-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_multamodel_pagomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('ANULADA', 'ANULADA')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sociomodel',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('TESORERO', 'TESORERO'), ('OPERADOR', 'OPERADOR'), ('SOCIO', 'SOCIO')], default='SOCIO', max_length=50),
        ),
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEDIDO', 'Medido (Con Medidor)'), ('FIJO', 'Tarifa Fija (Sin Medidor)')], default='FIJO', max_length=20)),
                ('valor_tarifa', models.DecimalField(decimal_places=2, default=3.0, help_text='Valor mensual para tarifa fija', max_digits=10)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='infrastructure.sociomodel')),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='infrastructure.terrenomodel')),
            ],
            options={
                'verbose_name': 'Servicio de Agua',
                'db_table': 'servicios_agua',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Vincula la factura al contrato de servicio específico (Fijo o Medido)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='infrastructure.serviciomodel'),
        ),
    ]
