# Generated by Django 5.2.7 on 2026-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_pagomodel_comprobante_imagen_pagomodel_validado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturamodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Año Fiscal'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Mes Fiscal'),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='Año Fiscal'),
        ),
        migrations.AddField(
            model_name='lecturamodel',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Mes Fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='facturamodel',
            unique_together={('servicio', 'anio', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturamodel',
            unique_together={('medidor', 'anio', 'mes')},
        ),
    ]
