# Generated by Django 5.2.7 on 2025-12-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_lecturamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturamodel',
            unique_together={('medidor', 'fecha')},
        ),
    ]
