# Generated by Django 5.2.10 on 2026-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_facturamodel_archivo_pdf_facturamodel_archivo_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomodel',
            name='tarifa_basica_m3',
            field=models.PositiveIntegerField(default=15, help_text='Metros cúbicos incluidos en la base (Ej: 15)'),
        ),
        migrations.AddField(
            model_name='serviciomodel',
            name='tarifa_excedente_precio',
            field=models.DecimalField(decimal_places=2, default=0.25, help_text='Costo por cada m³ adicional (Ej: 0.25)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviciomodel',
            name='valor_tarifa',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Costo de la Tarifa Básica (o Fija)', max_digits=10),
        ),
    ]
