# Generated by Django 5.2.7 on 2025-12-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_lecturamodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociomodel',
            old_name='barrio_domicilio',
            new_name='barrio',
        ),
    ]
