# Generated by Django 6.0.1 on 2026-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_serviciomodel_tarifa_basica_m3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciamodel',
            options={'verbose_name': 'Control de Asistencia', 'verbose_name_plural': 'Control de Asistencias'},
        ),
        migrations.RemoveField(
            model_name='asistenciamodel',
            name='asistio',
        ),
        migrations.AddField(
            model_name='asistenciamodel',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PRESENTE', 'PRESENTE'), ('FALTA', 'FALTA'), ('JUSTIFICADO', 'JUSTIFICADO')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistenciamodel',
            name='observacion',
            field=models.TextField(blank=True, help_text='Motivo de falta o justificacion', null=True),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'PROGRAMADA'), ('BORRADOR', 'BORRADOR'), ('FINALIZADO', 'FINALIZADO')], default='PROGRAMADA', max_length=20),
        ),
    ]
