# Generated by Django 5.2.10 on 2026-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_historicalmultamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRISecuencialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_establecimiento', models.CharField(default='001', max_length=3)),
                ('codigo_punto_emision', models.CharField(default='001', max_length=3)),
                ('tipo_comprobante', models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('05', 'NOTA DE DÉBITO'), ('06', 'GUÍA DE REMISIÓN'), ('07', 'RETENCIÓN')], max_length=2)),
                ('secuencia_actual', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secuencial SRI',
                'verbose_name_plural': 'Secuenciales SRI',
                'db_table': 'sri_secuenciales',
                'unique_together': {('codigo_establecimiento', 'codigo_punto_emision', 'tipo_comprobante')},
            },
        ),
    ]
