# Generated by Antigravity to initialize SRI sequences data safely

from django.db import migrations
from django.conf import settings

def initialize_sequences(apps, schema_editor):
    SRISecuencialModel = apps.get_model('infrastructure', 'SRISecuencialModel')
    
    # Intento de obtener configuración desde settings, con valores por defecto seguros
    # Nota: En migraciones, settings.SRI_SECUENCIA_INICIO puede no estar disponible si no se importó explícitamente
    # pero aquí importamos django.conf.settings
    initial_val = getattr(settings, 'SRI_SECUENCIA_INICIO', 600)
    estab = getattr(settings, 'SRI_SERIE_ESTABLECIMIENTO', '001')
    pto_emi = getattr(settings, 'SRI_SERIE_PUNTO_EMISION', '001')

    # Facturas (01)
    # Verificamos si ya existe para evitar errores en re-runs
    if not SRISecuencialModel.objects.filter(
        codigo_establecimiento=estab,
        codigo_punto_emision=pto_emi,
        tipo_comprobante='01'
    ).exists():
        SRISecuencialModel.objects.create(
            codigo_establecimiento=estab,
            codigo_punto_emision=pto_emi,
            tipo_comprobante='01',
            secuencia_actual=initial_val
        )

    # Notas de Crédito (04) - Se inicializa en 0
    if not SRISecuencialModel.objects.filter(
        codigo_establecimiento=estab,
        codigo_punto_emision=pto_emi,
        tipo_comprobante='04'
    ).exists():
        SRISecuencialModel.objects.create(
            codigo_establecimiento=estab,
            codigo_punto_emision=pto_emi,
            tipo_comprobante='04',
            secuencia_actual=0
        )

class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_srisecuencialmodel'),
    ]

    operations = [
        migrations.RunPython(initialize_sequences),
    ]
